import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FiCpu, FiMessageCircle, FiFileText, FiHelpCircle, 
  FiMic, FiSend, FiBookOpen, FiZap, 
  FiSave, FiTrash2, FiCopy, FiVolume2
} from 'react-icons/fi';
import toast from 'react-hot-toast';

const AIToolsHub = () => {
  const [activeTool, setActiveTool] = useState('chatbot');
  const [chatMessages, setChatMessages] = useState([
    { role: 'assistant', content: 'Hello! I\'m your AI study assistant. How can I help you today?', timestamp: new Date() }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  
  // Notes Generator
  const [topic, setTopic] = useState('');
  const [generatedNotes, setGeneratedNotes] = useState('');
  const [isGeneratingNotes, setIsGeneratingNotes] = useState(false);
  
  // Quiz Generator
  const [quizTopic, setQuizTopic] = useState('');
  const [generatedQuiz, setGeneratedQuiz] = useState([]);
  const [isGeneratingQuiz, setIsGeneratingQuiz] = useState(false);
  
  // Summary Tool
  const [summaryText, setSummaryText] = useState('');
  const [generatedSummary, setGeneratedSummary] = useState('');

  // AI Chatbot
  const handleSendMessage = async () => {
    if (!chatInput.trim()) return;
    
    const userMessage = { role: 'user', content: chatInput, timestamp: new Date() };
    setChatMessages(prev => [...prev, userMessage]);
    setChatInput('');
    setIsLoading(true);
    
    setTimeout(() => {
      const responses = {
        'react': 'React is a JavaScript library for building user interfaces. It uses a component-based architecture and virtual DOM for efficient rendering.',
        'javascript': 'JavaScript is a programming language that enables interactive web pages. It\'s an essential part of web development.',
        'python': 'Python is a high-level, interpreted programming language known for its simplicity and readability.',
        'default': 'I understand you\'re asking about ' + chatInput + '. Could you provide more details so I can help you better?'
      };
      
      let response = responses.default;
      for (const [key, value] of Object.entries(responses)) {
        if (chatInput.toLowerCase().includes(key)) {
          response = value;
          break;
        }
      }
      
      const assistantMessage = { role: 'assistant', content: response, timestamp: new Date() };
      setChatMessages(prev => [...prev, assistantMessage]);
      setIsLoading(false);
      toast.success('AI responded!');
    }, 1500);
  };

  // AI Notes Generator
  const handleGenerateNotes = async () => {
    if (!topic.trim()) {
      toast.error('Please enter a topic');
      return;
    }
    
    setIsGeneratingNotes(true);
    
    setTimeout(() => {
      const notes = `# ${topic} - Study Notes

## Introduction
${topic} is a fundamental concept in modern technology and education.

## Key Concepts
1. **Core Principles**: Understanding the basics of ${topic}
2. **Applications**: Real-world uses and implementations
3. **Best Practices**: Proven strategies for mastery

## Important Points
- ${topic} requires consistent practice
- Focus on understanding fundamentals
- Apply concepts through hands-on exercises

## Summary
${topic} is an essential skill for success. Keep practicing and exploring new concepts!

---
*Generated by AI Study Assistant*`;
      
      setGeneratedNotes(notes);
      setIsGeneratingNotes(false);
      toast.success('Notes generated successfully!');
    }, 2000);
  };

  // AI Quiz Generator
  const handleGenerateQuiz = async () => {
    if (!quizTopic.trim()) {
      toast.error('Please enter a topic');
      return;
    }
    
    setIsGeneratingQuiz(true);
    
    setTimeout(() => {
      const quiz = [
        { question: `What is the main purpose of ${quizTopic}?`, options: ['Option A', 'Option B', 'Option C', 'Option D'], correct: 0 },
        { question: `Which of the following best describes ${quizTopic}?`, options: ['Option A', 'Option B', 'Option C', 'Option D'], correct: 1 },
        { question: `When should you use ${quizTopic}?`, options: ['Option A', 'Option B', 'Option C', 'Option D'], correct: 2 },
      ];
      setGeneratedQuiz(quiz);
      setIsGeneratingQuiz(false);
      toast.success('Quiz generated! Check your knowledge.');
    }, 2000);
  };

  // AI Summary Generator
  const handleGenerateSummary = async () => {
    if (!summaryText.trim()) {
      toast.error('Please enter text to summarize');
      return;
    }
    
    setIsLoading(true);
    
    setTimeout(() => {
      const words = summaryText.split(' ');
      const summary = words.slice(0, Math.min(words.length / 3, 50)).join(' ') + '...';
      setGeneratedSummary(summary);
      setIsLoading(false);
      toast.success('Summary generated!');
    }, 1500);
  };

  const tools = [
    { id: 'chatbot', name: 'AI Chatbot', icon: FiMessageCircle, description: 'Get answers to your questions', color: 'from-purple-500 to-pink-500' },
    { id: 'notes', name: 'Notes Generator', icon: FiFileText, description: 'Generate study notes on any topic', color: 'from-blue-500 to-cyan-500' },
    { id: 'quiz', name: 'Quiz Generator', icon: FiHelpCircle, description: 'Create custom quizzes', color: 'from-green-500 to-emerald-500' },
    { id: 'summary', name: 'Summary Tool', icon: FiBookOpen, description: 'Summarize long texts', color: 'from-orange-500 to-red-500' },
  ];

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 pt-20">
      <div className="container mx-auto px-4 py-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold gradient-text">AI Tools Hub</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">Supercharge your learning with AI</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {tools.map(tool => {
            const Icon = tool.icon;
            return (
              <motion.button
                key={tool.id}
                whileHover={{ scale: 1.02 }}
                onClick={() => setActiveTool(tool.id)}
                className={`p-4 rounded-xl text-left transition-all ${activeTool === tool.id ? `bg-gradient-to-r ${tool.color} text-white shadow-lg` : 'bg-white dark:bg-gray-800 hover:shadow-lg'}`}
              >
                <Icon size={24} className={`mb-2 ${activeTool === tool.id ? 'text-white' : 'text-purple-600'}`} />
                <h3 className="font-bold">{tool.name}</h3>
                <p className={`text-sm ${activeTool === tool.id ? 'text-white/80' : 'text-gray-500'}`}>{tool.description}</p>
              </motion.button>
            );
          })}
        </div>

        <AnimatePresence mode="wait">
          <motion.div
            key={activeTool}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.3 }}
            className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl overflow-hidden"
          >
            {activeTool === 'chatbot' && (
              <div className="flex flex-col h-[600px]">
                <div className="flex-1 overflow-y-auto p-6 space-y-4">
                  {chatMessages.map((msg, idx) => (
                    <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                      <div className={`max-w-[70%] rounded-xl p-3 ${msg.role === 'user' ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700'}`}>
                        <p>{msg.content}</p>
                        <p className="text-xs opacity-70 mt-1">{new Date(msg.timestamp).toLocaleTimeString()}</p>
                      </div>
                    </div>
                  ))}
                  {isLoading && (
                    <div className="flex justify-start">
                      <div className="bg-gray-100 dark:bg-gray-700 rounded-xl p-3">
                        <div className="flex gap-1">
                          <div className="w-2 h-2 bg-gray-500 rounded-full animate-bounce"></div>
                          <div className="w-2 h-2 bg-gray-500 rounded-full animate-bounce delay-100"></div>
                          <div className="w-2 h-2 bg-gray-500 rounded-full animate-bounce delay-200"></div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
                <div className="border-t border-gray-200 dark:border-gray-700 p-4">
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                      placeholder="Ask me anything about your studies..."
                      className="flex-1 px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-500 outline-none"
                    />
                    <button
                      onClick={handleSendMessage}
                      disabled={isLoading}
                      className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition disabled:opacity-50"
                    >
                      <FiSend />
                    </button>
                  </div>
                </div>
              </div>
            )}

            {activeTool === 'notes' && (
              <div className="p-6">
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium mb-2">Topic / Subject</label>
                    <div className="flex gap-3">
                      <input
                        type="text"
                        value={topic}
                        onChange={(e) => setTopic(e.target.value)}
                        placeholder="e.g., React Hooks, Quantum Physics, JavaScript..."
                        className="flex-1 px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-500 outline-none"
                      />
                      <button
                        onClick={handleGenerateNotes}
                        disabled={isGeneratingNotes}
                        className="px-6 py-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:shadow-lg transition disabled:opacity-50 flex items-center gap-2"
                      >
                        {isGeneratingNotes ? '...' : <FiZap />}
                        Generate Notes
                      </button>
                    </div>
                  </div>
                  
                  {generatedNotes && (
                    <div className="border border-gray-200 dark:border-gray-700 rounded-lg p-6">
                      <div className="flex justify-between items-center mb-4">
                        <h3 className="font-bold">Generated Notes</h3>
                        <div className="flex gap-2">
                          <button onClick={() => navigator.clipboard.writeText(generatedNotes)} className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg">
                            <FiCopy />
                          </button>
                          <button className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg">
                            <FiSave />
                          </button>
                        </div>
                      </div>
                      <div className="prose dark:prose-invert max-w-none">
                        <pre className="whitespace-pre-wrap font-sans text-gray-700 dark:text-gray-300">
                          {generatedNotes}
                        </pre>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {activeTool === 'quiz' && (
              <div className="p-6">
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium mb-2">Quiz Topic</label>
                    <div className="flex gap-3">
                      <input
                        type="text"
                        value={quizTopic}
                        onChange={(e) => setQuizTopic(e.target.value)}
                        placeholder="e.g., JavaScript, React, Python..."
                        className="flex-1 px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-500 outline-none"
                      />
                      <button
                        onClick={handleGenerateQuiz}
                        disabled={isGeneratingQuiz}
                        className="px-6 py-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:shadow-lg transition disabled:opacity-50"
                      >
                        {isGeneratingQuiz ? 'Generating...' : 'Generate Quiz'}
                      </button>
                    </div>
                  </div>
                  
                  {generatedQuiz.length > 0 && (
                    <div className="space-y-4">
                      <h3 className="font-bold text-lg">Generated Quiz</h3>
                      {generatedQuiz.map((q, idx) => (
                        <div key={idx} className="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                          <p className="font-medium mb-3">{idx + 1}. {q.question}</p>
                          <div className="space-y-2">
                            {q.options.map((opt, optIdx) => (
                              <label key={optIdx} className="flex items-center gap-2 p-2 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer">
                                <input type="radio" name={`q${idx}`} className="text-purple-600" />
                                <span className="text-sm">{opt}</span>
                              </label>
                            ))}
                          </div>
                        </div>
                      ))}
                      <button className="w-full py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition">
                        Submit Quiz
                      </button>
                    </div>
                  )}
                </div>
              </div>
            )}

            {activeTool === 'summary' && (
              <div className="p-6">
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium mb-2">Text to Summarize</label>
                    <textarea
                      value={summaryText}
                      onChange={(e) => setSummaryText(e.target.value)}
                      placeholder="Paste your long text here... The AI will create a concise summary..."
                      rows={6}
                      className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-500 outline-none resize-none"
                    />
                  </div>
                  
                  <button
                    onClick={handleGenerateSummary}
                    disabled={isLoading}
                    className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:shadow-lg transition disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    {isLoading ? 'Summarizing...' : <FiZap />}
                    Generate Summary
                  </button>
                  
                  {generatedSummary && (
                    <div className="border border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20 rounded-lg p-6">
                      <h3 className="font-bold text-green-600 mb-2">AI Summary</h3>
                      <p className="text-gray-700 dark:text-gray-300">{generatedSummary}</p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
};

export default AIToolsHub;